# ---------- Stage 1 : Build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy dependencies
COPY package*.json ./
RUN npm ci


COPY . .

# Build
RUN npm run build

# ---------- Stage 2 : Runtime ----------
FROM nginx:alpine

# Copy the build
COPY --from=builder /app/dist /usr/share/nginx/html

# Apply nginx config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

# Exposer le port 80
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
