# ---------- Stage 1: build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci

# Copier le reste du projet
COPY . .

# Build de la PWA
RUN npm run build

# ---------- Stage 2: output build ----------
FROM alpine:latest AS runner

# Copier le build vers /build pour Nginx
COPY --from=builder /app/dist /build

