# ---------- Stage 1: build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the project
COPY . .

# Build the app
RUN npm run build

# ---------- Stage 2: runtime ----------
FROM nginx:alpine

# Copu the build from stage 1
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy personal nginx config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
