# ---------- Stage 1: build ----------
FROM node:20-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm ci

# Copier le reste du projet
COPY . .

# Construire l’application
RUN npm run build

# ---------- Stage 2: dummy (build-only container) ----------
FROM alpine:latest AS runner

# Copier le build pour le mettre à disposition
COPY --from=builder /app/dist /build

